# Dependencies
markdown:         kramdown
highlighter:      pygments

theme: jekyll-theme-tactile

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Plugins
gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

# Setup
title:            Network Automation!
tagline:          'Brownfield (mostly)'
description:      'Observations in network automation<br /> <a href="https://twitter.com/geralddykeman" target="_blank">@geralddykeman</a>'
url:              http://gdykeman.github.io
baseurl:          /

author:
  name:           'Gerald Dykeman'
  url:            https://twitter.com/geralddykeman

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gdykeman
