# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Network Automation
tagline:          'Brownfield (mostly)'
description:      'Gerald Dykeman<br /> CCIE #36354'
url:              http://gdykeman.github.io
baseurl:          /

author:
  name:           'Gerald Dykeman'
  url:            https://twitter.com/geralddykeman
  linkedin:       https://linkedin.com/u/gdykeman

paginate:         5

excerpt_separator: "<!--more-->"

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

#Archive
pages_list:
  Archive: '/archive'

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/gdykeman

theme: jekyll-theme-minimal
