# Dependencies
markdown:         kramdown
highlighter:      pygments

theme: jekyll-theme-tactile

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Plugins
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-remote-theme

# Setup
title:            Network Automation!
tagline:          'Brownfield (mostly)'
description:      'Gerald Dykeman <br />CCIE #366354'
url:              http://gdykeman.github.io
baseurl:          /

author:
  name:           'Gerald Dykeman'
  url:            https://twitter.com/geralddykeman

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gdykeman
